# -*- coding: utf-8 -*-
"""Artificial_Intillegence.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TXum7KHTUxxkLUazioLc99rHDRwNxTgB
"""

#Displaying Hello World
X=str("Hello World!")
print(X)