# -*- coding: utf-8 -*-
"""diffrent_Operations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TXum7KHTUxxkLUazioLc99rHDRwNxTgB
"""

# Program to perform different set operations
# as we do in  mathematics

# sets are define
A = {0, 2, 4, 6, 8};
B = {1, 2, 3, 4, 5};

# union
print("Union :", A | B)

# intersection
print("Intersection :", A & B)

# difference
print("Difference :", A - B)

# symmetric difference
print("Symmetric difference :", A ^ B)